# game window resolution
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

# Asteroid related constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # in seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_COLOR = "red"
ASTEROID_LINE_WIDTH = 2

# Player related constants
PLAYER_RADIUS = 20
PLAYER_COLOR = "white"
PLAYER_LINE_WIDTH = 2
PLAYER_START_POS_X = SCREEN_WIDTH / 2
PLAYER_START_POS_Y = SCREEN_HEIGHT / 2
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
